test_format = 1.0

[default]

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    args.admin = "admin"

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.d9beaa2fa546a3c2acce2457d8d817bcbbbdd520.name = "Upgrade from 1.2.35~ynh3"
