test_format = 1.0

[default]

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    args.admin = "admin"

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.781f62a9.name = "Upgrade from 1.2.22"
