#!/bin/bash
app=kanboard

# Retrieve arguments
domain=$1
path=$2
admin=$3

# Retrieve admin email
email=$(sudo yunohost user info $admin | grep mail: | sed "s/mail: //g")

# Check domain/path availability
sudo yunohost app checkurl $domain$path -a $app
if [[ ! $? -eq 0 ]]; then
    exit 1
fi

# Generate random password
db_pwd=$(openssl rand -hex 15)

# Initialize database and store mysql password for upgrade
sudo yunohost app initdb $app -p $db_pwd
sudo yunohost app setting $app mysqlpwd -v $db_pwd
sudo yunohost app setting $app adminusername -v $admin

# Copy sources
final_path=/var/www/$app
sudo mkdir -p $final_path
sudo cp -a ../sources/* $final_path

# Copy and edit config.php
sudo cp ../conf/config.php $final_path
sudo sed -i "s/yuno_dbpdw/$db_pwd/g" $final_path/config.php
sudo sed -i "s/yuno_dbuser/$app/g" $final_path/config.php
sudo sed -i "s/yuno_admin/$admin/g" $final_path/config.php
sudo sed -i "s/yuno_email/$email/g" $final_path/config.php
sudo sed -i "s/yuno_domain/$domain/g" $final_path/config.php

# Set permissions to data directory and config file
sudo chown -R www-data:www-data $final_path/data
sudo chown www-data:www-data $final_path/config.php

# Modify Nginx configuration file and copy it to Nginx conf directory
sed -i "s@PATHTOCHANGE@$path@g" ../conf/nginx.conf*
sed -i "s@ALIASTOCHANGE@$final_path/@g" ../conf/nginx.conf*
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf

# Reload Nginx and regenerate SSOwat conf
sudo service nginx reload
sudo yunohost app ssowatconf