#!/bin/bash

# Source local helpers
source ./_common.sh

# Source app helpers
source /usr/share/yunohost/helpers

# Abort script if errors
ynh_abort_if_errors

# Retrieve arguments
domain=$YNH_APP_ARG_DOMAIN
path=$YNH_APP_ARG_PATH
admin=$YNH_APP_ARG_ADMIN
is_public=$YNH_APP_ARG_IS_PUBLIC

app=$YNH_APP_INSTANCE_NAME

# Normalize the url path syntax
path=$(ynh_normalize_url_path "$path")

# Check web path availability
ynh_webpath_available "$domain" "$path"
# Register (book) web path
ynh_webpath_register "$app" "$domain" "$path"

ynh_app_setting_set $app admin_user $admin

# Retrieve admin email
email=$(ynh_user_get_info "$admin" mail)

# Check destination directory
final_path="/var/www/$app"
test ! -e "$final_path" || ynh_die "This path already contains a folder"

ynh_app_setting_set $app final_path $final_path

# Generate random password
dbpass=$(ynh_string_random)
dbname=$app
dbuser=$app

# Initialize database and store mysql password for upgrade
ynh_mysql_create_db "$dbname" "$dbuser" "$dbpass"
ynh_app_setting_set $app mysqlpwd $dbpass
ynh_app_setting_set $app adminusername $admin
ynh_app_setting_set $app is_public $is_public

ynh_setup_source "$final_path"

# Copy and edit config.php
config_php="${final_path}/config.php"

cp ../conf/config.php "$config_php"
ynh_replace_string "yuno_dbpdw"  "$dbpass" "$config_php"
ynh_replace_string "yuno_dbuser" "$dbuser" "$config_php"
ynh_replace_string "yuno_admin"  "$admin"  "$config_php"
ynh_replace_string "yuno_email"  "$email"  "$config_php"
ynh_replace_string "yuno_domain" "$domain" "$config_php"

# Set permissions to kanboard and data directory
chown -R root:root ${final_path}
chown -R www-data ${final_path}/{data,plugins}

# Copy and set php-fpm configuration
phpfpm_conf="/etc/php5/fpm/pool.d/${app}.conf"

cp ../conf/php-fpm.conf "$phpfpm_conf"
ynh_replace_string "#POOLNAME#" "$app"        "$phpfpm_conf"
ynh_replace_string "#DESTDIR#"  "$final_path" "$phpfpm_conf"

chown root: $phpfpm_conf
chmod 644 $phpfpm_conf

finalnginxconf="/etc/nginx/conf.d/${domain}.d/${app}.conf"
cp ../conf/nginx.conf "$finalnginxconf"

# Modify Nginx configuration file and copy it to Nginx conf directory
ynh_replace_string "NAMETOCHANGE"  "$app"        "$finalnginxconf"
ynh_replace_string "PATHTOCHANGE"  "$path"       "$finalnginxconf"
ynh_replace_string "ALIASTOCHANGE" "$final_path" "$finalnginxconf"

if [ "$path" == "/" ]
then
	# ynh panel is only comptable with non-root installation
	ynh_replace_string "	include conf.d/"  "	#include conf.d/"  "$finalnginxconf"
fi

# Make app public or private
if [[ "$is_public" -eq 1 ]];
then
	ynh_app_setting_set "$app" unprotected_uris "/"
	ynh_replace_string "define('LDAP_AUTH'.*$"        "define('LDAP_AUTH', true);"        "$config_php"
	ynh_replace_string "define('HIDE_LOGIN_FORM'.*$"  "define('HIDE_LOGIN_FORM', false);" "$config_php"
	ynh_replace_string "define('REMEMBER_ME_AUTH'.*$" "define('REMEMBER_ME_AUTH', true);" "$config_php"
	ynh_replace_string "define('DISABLE_LOGOUT'.*$"   "define('DISABLE_LOGOUT', false);"  "$config_php"
fi

# Init database
ynh_mysql_connect_as "$dbuser" "$dbpass" "$dbname" < ${final_path}/app/Schema/Sql/mysql.sql

# Reload services
service php5-fpm restart || true
service nginx reload || true
