#!/bin/bash

# Source local helpers
source ./_common.sh

# Source app helpers
source /usr/share/yunohost/helpers

app="kanboard"

dbname=$app
dbuser=$app

# Drop MySQL database and user
ynh_mysql_drop_db "$dbname" 2>/dev/null || true
ynh_mysql_drop_user "$dbuser" 2>/dev/null || true

# Retrieve domain from app settings
domain=$(ynh_app_setting_get "$app" domain)

# Delete app directory and configurations
rm -rf "/var/www/${app}"
rm -f "/etc/php5/fpm/pool.d/${app}.conf"
[[ -n $domain ]] && rm -f "/etc/nginx/conf.d/${domain}.d/${app}.conf"

# Reload services
service php5-fpm restart || true
service nginx reload || true
