#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression "Ensuring downward compatibility..."

# If upgrading from 1.2.52~ynh2 or below
ynh_app_setting_set_default --key=php_upload_max_filesize --value=100M
ynh_app_setting_set_default --key=ldap_auth --value=false
ynh_app_setting_set_default --key=hide_login_form --value=false
ynh_app_setting_set_default --key=disable_logout --value=false

# Load settings for config.php template
ldap_auth=$(ynh_app_setting_get --key=ldap_auth)
hide_login_form=$(ynh_app_setting_get --key=hide_login_form)
disable_logout=$(ynh_app_setting_get --key=disable_logout)

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --keep="config.php"

mkdir -p $install_dir/sessions/

chmod -R 700 $install_dir/sessions

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_phpfpm

ynh_config_add_nginx

ynh_config_add_fail2ban --logpath="/var/log/nginx/${domain}-error.log" --failregex="^.*authentication failure\" while reading response header from upstream, client: <HOST>,.*$"

ynh_config_add --template="cron" --destination="/etc/cron.d/$app"

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

dir="__DIR__"
ynh_config_add --template="config.php" --destination="$install_dir/config.php"

#=================================================
# UPGRADE KANBOARD
#=================================================
ynh_script_progression "Upgrading the app..."

pushd $install_dir
	php$php_version cli db:migrate --no-interaction --verbose
popd

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
