#!/bin/bash

set -e
app=kanboard

# Retrieve settings
domain=$(sudo yunohost app setting $app domain)
path=$(sudo yunohost app setting $app path)
admin=$(sudo yunohost app setting $app adminusername)
email=$(sudo yunohost user info $admin | grep mail: | sed "s/mail: //g")
db_pwd=$(sudo yunohost app setting $app mysqlpwd)

final_path=/var/www/$app
sudo mv $final_path $final_path.old

sudo mkdir -p $final_path
sudo cp -a ../sources/. $final_path
sudo cp -a $final_path.old/data $final_path/data
sudo rm -Rf $final_path.old

# Copy and edit config.php
sudo cp ../conf/config.php $final_path
sudo sed -i "s/yuno_dbpdw/$db_pwd/g" $final_path/config.php
sudo sed -i "s/yuno_dbuser/$app/g" $final_path/config.php
sudo sed -i "s/yuno_admin/$admin/g" $final_path/config.php
sudo sed -i "s/yuno_email/$email/g" $final_path/config.php
sudo sed -i "s/yuno_domain/$domain/g" $final_path/config.php

# Set permissions to kanboard and data directory
sudo chown -R root:root $final_path
sudo chown -R www-data:www-data $final_path/data

# Use dedicated php pool
sed -i "s@NAMETOCHANGE@$app@g" ../conf/php-fpm.conf
finalphpconf=/etc/php5/fpm/pool.d/$app.conf
sudo cp ../conf/php-fpm.conf $finalphpconf
sudo chown root: $finalphpconf
sudo chmod 644 $finalphpconf

# Modify Nginx configuration file and copy it to Nginx conf directory
sed -i "s@NAMETOCHANGE@$app@g" ../conf/nginx.conf*
sed -i "s@PATHTOCHANGE@$path@g" ../conf/nginx.conf*
sed -i "s@ALIASTOCHANGE@$final_path/@g" ../conf/nginx.conf*
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf

# Reload Nginx, PHP5-FPM and regenerate SSOwat conf
sudo service php5-fpm restart
sudo service nginx reload
sudo yunohost app ssowatconf